[package]
name = "my-example"
version = "0.1.0"
authors = ["Shunsuke Watanabe <ww.shunsuke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
error-chain = "0.12.2"
rand_distr = "0.2.2"
